name: cd

on:
  push:
    branches: [staging]

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2       
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
