name: Sync multiple branches
on:
  push:
    branches:
      - "staging"
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge staging -> uat
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: staging
          target_branch: main
          github_token: ${{ github.token }}
